# This is a basic workflow takes care of building and deploying
# catalog when pushing to main branch

# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pages: write
      pull-requests: write
      packages: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Build
        run: |
          docker run -v "$PWD:/workspace" -w "/workspace" ghcr.io/eodash/eodash_catalog:0.4.6 eodash_catalog -gp
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          folder: ./build
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
